name: strong_security
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  flutter_native_splash: ^2.3.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.4.0
  geocoding: ^2.1.0
  location: ^5.0.3
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  http: ^1.1.0
  fluttertoast: ^8.2.2
  get: ^4.6.5
  image_picker: ^1.0.4
  flutter_local_notifications: ^16.1.0
  awesome_notifications: ^0.7.4+1


flutter_native_splash:
  color: "#ffffff"
  image: "images/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true

  assets:
     - images/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Bold.ttf
        - asset: asset/fonts/Poppins-Black.ttf
flutter_icons:
  image_path_ios: 'images/images/logo.png'
  image_path_android: 'images/images/logo.png'
  android: true
  ios: true
