
class CountList  {

   List<String> customCountryList = [
     'Afghanistan',
     'Albania',
     'Algeria',
     'Andorra',
     'Angola',
     'Argentina',
     'Armenia',
     'Austria',
     'Azerbaijan',
     'Bahrain',
     'Bangladesh',
     'Barbados',
     'Belarus',
     'Belgium',
     'Belize',
     'Benin',
     'Bhutan',
     'Bolivia',
     'Botswana',
     'Brazil',
     'Brunei',
     'Bulgaria',
     'Burkina Faso',
     'Burundi',
     'Cabo Verde',
     'Cambodia',
     'Cameroon',
     'Canada',

     'Chad',
     'Channel Islands',
     'Chile',
     'China',
     'Colombia',
     'Comoros',
     'Congo',
     'Costa Rica',
     'Côte d\'Ivoire',
     'Croatia',
     'Cuba',
     'Cyprus',
     'Czech Republic',
     'Denmark',
     'Djibouti',
     'Dominica',
     'Dominican Republic',
     'DR Congo',
     'Ecuador',
     'Egypt',
     'El Salvador',
     'Equatorial Guinea',
     'Eritrea',
     'Estonia',
     'Eswatini',
     'Ethiopia',
     'Faeroe Islands',
     'Finland',
     'France',
     'French Guiana',
     'Gabon',
     'Gambia',
     'Georgia',
     'Germany',
     'Ghana',
     'Gibraltar',
     'Greece',
     'Grenada',
     'Guatemala',
     'Guinea',
     'Guinea-Bissau',
     'Guyana',
     'Haiti',
     'Holy See',
     'Honduras',
     'Hong Kong',
     'Hungary',
     'Iceland',
     'India',
     'Indonesia',
     'Iran',
     'Iraq',
     'Ireland',
     'Isle of Man',
     'Israel',
     'Italy',
     'Jamaica',
     'Japan',
     'Jordan',
     'Kazakhstan',
     'Kenya',
     'Kuwait',
     'Kyrgyzstan',
     'Laos',
     'Latvia',
     'Lebanon',
     'Lesotho',
     'Liberia',
     'Libya',
     'Liechtenstein',
     'Lithuania',
     'Luxembourg',
     'Macao',
     'Madagascar',
     'Malawi',
     'Malaysia',
     'Maldives',
     'Mali',
     'Malta',
     'Mauritania',
     'Mauritius',
     'Mayotte',
     'Mexico',
     'Moldova',
     'Monaco',
     'Mongolia',
     'Montenegro',
     'Morocco',
     'Mozambique',
     'Myanmar',
     'Namibia',
     'Nepal',
     'Netherlands',
     'Nicaragua',
     'Niger',
     'Nigeria',
     'North Korea',
     'North Macedonia',
     'Norway',
     'Oman',
     'Pakistan',
     'Panama',
     'Paraguay',
     'Peru',
     'Philippines',
     'Poland',
     'Portugal',
     'Qatar',
     'Réunion',
     'Romania',
     'Russia',
     'Rwanda',
     'Saint Helena',
     'Saint Kitts ',
     'Saint Lucia',
     'Saint Vincent ',
     'San Marino',
     'Sao Tome ',
     'Saudi Arabia',
     'Senegal',
     'Serbia',
     'Seychelles',
     'Sierra Leone',
     'Singapore',
     'Slovakia',
     'Slovenia',
     'Somalia',
     'South Africa',
     'South Korea',
     'South Sudan',
     'Spain',
     'Sri Lanka',
     'State of Palestine',
     'Sudan',
     'Suriname',
     'Sweden',
     'Switzerland',
     'Syria',
     'Taiwan',
     'Tajikistan',
     'Tanzania',
     'Thailand',
     'The Bahamas',
     'Timor-Leste',
     'Togo',
     'Trinidad',
     'Tunisia',
     'Turkey',
     'Turkmenistan',
     'Uganda',
     'Ukraine',
     'UAE',
     'United Kingdom',
     'United States',
     'Uruguay',
     'Uzbekistan',
     'Venezuela',
     'Vietnam',
     'Western Sahara',
     'Yemen',
     'Zambia',
     'Zimbabwe',
   ];

   List<String> subcityCountryList = [

     'Addis Ketema',
     'Akaky Kaliti',
     'Arada',
     'Bole',
     'Gullele',
     'Kirkos',
     'Kolfe Keranio',
     'Lideta',


   ];
}

